import os
import re
import datetime
import logging
from schemas import TripItinerary

logger = logging.getLogger("OutputManager")
TRIPS_DIR = "trips"

def save_itinerary_to_markdown(itinerary: TripItinerary) -> str | None:
    """
    Receives a TripItinerary object and generates a formatted Markdown file.
    Returns the filename if successful, or None if it fails.
    """
    try:
        # Ensure trips directory exists
        os.makedirs(TRIPS_DIR, exist_ok=True)
        
        # Create a safe filename (e.g., "Paris_France_Itinerary.md")
        safe_dest = re.sub(r'[^a-zA-Z0-9]', '_', itinerary.destination)
        date_time = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = os.path.join(TRIPS_DIR, f"{safe_dest}_Itinerary_{date_time}.md")
        
        # Build the Markdown content
        md_content = f"""# ✈️ Trip Itinerary: {itinerary.destination}

> **Generated by Agentic Travel Architect**
> *Date: {datetime.datetime.now().strftime("%Y-%m-%d")}*

## 📝 Overview
{itinerary.overview}

---

## 📍 Daily Schedule

"""
        
        for day in itinerary.itinerary:
            md_content += f"### 📅 Day {day.day}: {day.theme}\n\n"
            
            for act in day.activities:
                md_content += f"#### ⏰ {act.time} | {act.title}\n"
                md_content += f"{act.description}\n\n"
            
            md_content += "---\n\n"
            
        md_content += "\n*Have a wonderful trip! 🌍*"

        # Save to file
        with open(filename, "w", encoding="utf-8") as f:
            f.write(md_content)
            
        logger.info(f"Markdown file successfully generated: {filename}")
        return filename

    except Exception as e:
        logger.error(f"Failed to save Markdown file: {e}")
        return None