from typing import List
from pydantic import BaseModel, Field


class SearchStrategy(BaseModel):
    """
    Defines the plan of action for retrieving tourist information.
    This object is generated by the Planner and must be approved by the user.
    """
    reasoning: str = Field(
        ..., 
        description="Explanation of why these specific searches are necessary based on the user's request."
    )
    queries: List[str] = Field(
        ..., 
        description="List of exact search queries that will be sent to the MCP server."
    )


class Activity(BaseModel):
    time: str = Field(..., description="Suggested time window, e.g., '09:00 - 11:00'")
    title: str = Field(..., description="Name of the activity or location")
    description: str = Field(..., description="Brief description of what to do there")

class DayPlan(BaseModel):
    day: int = Field(..., description="Day number (1, 2, etc.)")
    theme: str = Field(..., description="Main theme of the day, e.g., 'History & Culture' or 'Gastronomy'")
    activities: List[Activity]

class TripItinerary(BaseModel):
    """
    The final object containing the complete tourist recommendation.
    """
    destination: str = Field(..., description="City/Country of destination")
    overview: str = Field(..., description="General summary of the proposed experience")
    itinerary: List[DayPlan]